apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  labels:
    release: stable
    capacity: 100Gi
spec:
  capacity:
    storage: 10Gi
  volumeMode: ext4
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /tmp
    server: 172.17.0.2

